import { CountryId, FieldCategory, FieldDefinition } from "./types";
import { extractPlusTag, generateDebugEmail } from "../generators/email";
import {
  generateFrenchIBAN,
  generateFrenchPhoneNumber,
  generateFrenchPostalCode,
  generateFrenchSIREN,
  generateFrenchVAT,
} from "../generators/france";
import {
  generateGermanIBAN,
  generateGermanPhoneNumber,
  generateGermanPostalCode,
  generateGermanVAT,
} from "../generators/germany";
import {
  formatCardNumber,
  generateCardCvc,
  generateCardExpiry,
  generateMasterCard,
  generateStripeTestCard,
  generateVisaCard,
} from "../generators/payment";
import {
  generateFrenchBirthDate,
  generateFrenchCity,
  generateFrenchCompanyName,
  generateFrenchFirstName,
  generateFrenchFullName,
  generateFrenchLastName,
  generateFrenchStreet,
  generateGermanBirthDate,
  generateGermanCity,
  generateGermanCompanyName,
  generateGermanFirstName,
  generateGermanFullName,
  generateGermanLastName,
  generateGermanStreet,
  generatePolishBirthDate,
  generatePolishCity,
  generatePolishCompanyName,
  generatePolishFirstName,
  generatePolishFullName,
  generatePolishLastName,
  generatePolishPostalCode,
  generatePolishStreet,
  generateUKBirthDate,
  generateUKCity,
  generateUKCompanyName,
  generateUKFirstName,
  generateUKFullName,
  generateUKLastName,
  generateUKStreet,
  generateUSBirthDate,
  generateUSCity,
  generateUSCompanyName,
  generateUSFirstName,
  generateUSFullName,
  generateUSLastName,
  generateUSState,
  generateUSStreet,
  generateUSZip,
} from "../generators/person";
import {
  generateRandomNIP,
  generateRandomPESEL,
  generateRandomPolishIBAN,
  generateRandomPolishPhoneNumber,
  generateRandomPolishPlateNumber,
  generateRandomPolishVAT,
  generateRandomREGON,
} from "../generators/poland";
import { generateUuid } from "../generators/tracking";
import { generateUKIBAN, generateUKPhoneNumber, generateUKPostalCode, generateUKVAT } from "../generators/uk";
import { generateRandomSSN, generateRandomUSPhoneNumber } from "../generators/usa";

export const categoryOrder: FieldCategory[] = [
  "tracking",
  "identity",
  "contact",
  "address",
  "company",
  "payment",
  "vehicle",
];

export const categoryTitles: Record<FieldCategory, string> = {
  tracking: "Tracking",
  identity: "Identity",
  contact: "Contact",
  address: "Address",
  company: "Company",
  payment: "Payment",
  vehicle: "Vehicle",
};

function digitsOnly(value: string): string {
  return value.replace(/\D/g, "");
}

function spacedPolishPhone(value: string): string {
  const digits = digitsOnly(value).replace(/^48/, "");
  return `+48 ${digits.slice(0, 3)} ${digits.slice(3, 6)} ${digits.slice(6)}`;
}

function spacedUSPhone(value: string): string {
  const digits = digitsOnly(value).replace(/^1/, "");
  return `+1 (${digits.slice(0, 3)}) ${digits.slice(3, 6)}-${digits.slice(6)}`;
}

export const fieldCatalog: FieldDefinition[] = [
  {
    id: "debug-email",
    title: "Your debug email",
    accessory: "Plus-addressed tester email",
    category: "tracking",
    countries: "global",
    generator: generateDebugEmail,
    copyVariants: [
      { title: "Copy plus tag", transform: extractPlusTag },
      { title: "Copy local part", transform: (value) => value.split("@")[0] ?? value },
    ],
  },
  {
    id: "uuid",
    title: "UUID",
    accessory: "Unique session / order id",
    category: "tracking",
    countries: "global",
    generator: generateUuid,
  },
  {
    id: "first-name-pl",
    title: "Imię",
    accessory: "Polish first name",
    category: "identity",
    countries: ["poland"],
    generator: generatePolishFirstName,
  },
  {
    id: "last-name-pl",
    title: "Nazwisko",
    accessory: "Polish last name",
    category: "identity",
    countries: ["poland"],
    generator: generatePolishLastName,
  },
  {
    id: "full-name-pl",
    title: "Imię i nazwisko",
    accessory: "Polish full name",
    category: "identity",
    countries: ["poland"],
    generator: generatePolishFullName,
  },
  {
    id: "birth-date-pl",
    title: "Data urodzenia",
    accessory: "Format DD.MM.YYYY",
    category: "identity",
    countries: ["poland"],
    generator: generatePolishBirthDate,
    copyVariants: [{ title: "Copy ISO date", transform: (value) => value.split(".").reverse().join("-") }],
  },
  {
    id: "pesel",
    title: "PESEL",
    accessory: "National identification number",
    category: "identity",
    countries: ["poland"],
    generator: generateRandomPESEL,
  },
  {
    id: "first-name-de",
    title: "Vorname",
    accessory: "German first name",
    category: "identity",
    countries: ["germany"],
    generator: generateGermanFirstName,
  },
  {
    id: "last-name-de",
    title: "Nachname",
    accessory: "German last name",
    category: "identity",
    countries: ["germany"],
    generator: generateGermanLastName,
  },
  {
    id: "full-name-de",
    title: "Vorname und Nachname",
    accessory: "German full name",
    category: "identity",
    countries: ["germany"],
    generator: generateGermanFullName,
  },
  {
    id: "birth-date-de",
    title: "Geburtsdatum",
    accessory: "Format DD.MM.YYYY",
    category: "identity",
    countries: ["germany"],
    generator: generateGermanBirthDate,
    copyVariants: [{ title: "Copy ISO date", transform: (value) => value.split(".").reverse().join("-") }],
  },
  {
    id: "first-name-uk",
    title: "First name",
    accessory: "UK first name",
    category: "identity",
    countries: ["uk"],
    generator: generateUKFirstName,
  },
  {
    id: "last-name-uk",
    title: "Last name",
    accessory: "UK last name",
    category: "identity",
    countries: ["uk"],
    generator: generateUKLastName,
  },
  {
    id: "full-name-uk",
    title: "Full name",
    accessory: "UK full name",
    category: "identity",
    countries: ["uk"],
    generator: generateUKFullName,
  },
  {
    id: "birth-date-uk",
    title: "Date of birth",
    accessory: "Format DD/MM/YYYY",
    category: "identity",
    countries: ["uk"],
    generator: generateUKBirthDate,
    copyVariants: [{ title: "Copy ISO date", transform: (value) => value.split("/").reverse().join("-") }],
  },
  {
    id: "first-name-fr",
    title: "Prénom",
    accessory: "French first name",
    category: "identity",
    countries: ["france"],
    generator: generateFrenchFirstName,
  },
  {
    id: "last-name-fr",
    title: "Nom",
    accessory: "French last name",
    category: "identity",
    countries: ["france"],
    generator: generateFrenchLastName,
  },
  {
    id: "full-name-fr",
    title: "Prénom et nom",
    accessory: "French full name",
    category: "identity",
    countries: ["france"],
    generator: generateFrenchFullName,
  },
  {
    id: "birth-date-fr",
    title: "Date de naissance",
    accessory: "Format DD/MM/YYYY",
    category: "identity",
    countries: ["france"],
    generator: generateFrenchBirthDate,
    copyVariants: [{ title: "Copy ISO date", transform: (value) => value.split("/").reverse().join("-") }],
  },
  {
    id: "first-name-us",
    title: "First name",
    accessory: "US first name",
    category: "identity",
    countries: ["usa"],
    generator: generateUSFirstName,
  },
  {
    id: "last-name-us",
    title: "Last name",
    accessory: "US last name",
    category: "identity",
    countries: ["usa"],
    generator: generateUSLastName,
  },
  {
    id: "full-name-us",
    title: "Full name",
    accessory: "US full name",
    category: "identity",
    countries: ["usa"],
    generator: generateUSFullName,
  },
  {
    id: "birth-date-us",
    title: "Date of birth",
    accessory: "Format MM/DD/YYYY",
    category: "identity",
    countries: ["usa"],
    generator: generateUSBirthDate,
  },
  {
    id: "ssn",
    title: "SSN",
    accessory: "Social Security Number",
    category: "identity",
    countries: ["usa"],
    generator: generateRandomSSN,
    copyVariants: [{ title: "Copy without dashes", transform: digitsOnly }],
  },
  {
    id: "phone-pl",
    title: "Numer telefonu",
    accessory: "Polish mobile number",
    category: "contact",
    countries: ["poland"],
    generator: generateRandomPolishPhoneNumber,
    copyVariants: [
      { title: "Copy national format", transform: (value) => digitsOnly(value).replace(/^48/, "") },
      { title: "Copy spaced E.164", transform: spacedPolishPhone },
    ],
  },
  {
    id: "phone-us",
    title: "Phone number",
    accessory: "US phone number",
    category: "contact",
    countries: ["usa"],
    generator: generateRandomUSPhoneNumber,
    copyVariants: [
      { title: "Copy national format", transform: (value) => digitsOnly(value).replace(/^1/, "") },
      { title: "Copy spaced E.164", transform: spacedUSPhone },
    ],
  },
  {
    id: "phone-de",
    title: "Telefonnummer",
    accessory: "German mobile number",
    category: "contact",
    countries: ["germany"],
    generator: generateGermanPhoneNumber,
    copyVariants: [{ title: "Copy national format", transform: (value) => `0${digitsOnly(value).replace(/^49/, "")}` }],
  },
  {
    id: "phone-uk",
    title: "Phone number",
    accessory: "UK mobile number",
    category: "contact",
    countries: ["uk"],
    generator: generateUKPhoneNumber,
    copyVariants: [{ title: "Copy national format", transform: (value) => `0${digitsOnly(value).replace(/^44/, "")}` }],
  },
  {
    id: "phone-fr",
    title: "Numéro de téléphone",
    accessory: "French mobile number",
    category: "contact",
    countries: ["france"],
    generator: generateFrenchPhoneNumber,
    copyVariants: [{ title: "Copy national format", transform: (value) => `0${digitsOnly(value).replace(/^33/, "")}` }],
  },
  {
    id: "street-pl",
    title: "Ulica",
    accessory: "Street and number",
    category: "address",
    countries: ["poland"],
    generator: generatePolishStreet,
  },
  {
    id: "postal-pl",
    title: "Kod pocztowy",
    accessory: "5-digit postal code (XX-XXX)",
    category: "address",
    countries: ["poland"],
    generator: generatePolishPostalCode,
  },
  {
    id: "city-pl",
    title: "Miasto",
    accessory: "Polish city",
    category: "address",
    countries: ["poland"],
    generator: generatePolishCity,
  },
  {
    id: "street-de",
    title: "Straße",
    accessory: "Street and number",
    category: "address",
    countries: ["germany"],
    generator: generateGermanStreet,
  },
  {
    id: "postal-de",
    title: "Postleitzahl",
    accessory: "5-digit postal code",
    category: "address",
    countries: ["germany"],
    generator: generateGermanPostalCode,
  },
  {
    id: "city-de",
    title: "Stadt",
    accessory: "German city",
    category: "address",
    countries: ["germany"],
    generator: generateGermanCity,
  },
  {
    id: "street-uk",
    title: "Street",
    accessory: "UK street address",
    category: "address",
    countries: ["uk"],
    generator: generateUKStreet,
  },
  {
    id: "postal-uk",
    title: "Postcode",
    accessory: "UK postcode",
    category: "address",
    countries: ["uk"],
    generator: generateUKPostalCode,
  },
  {
    id: "city-uk",
    title: "City",
    accessory: "UK city",
    category: "address",
    countries: ["uk"],
    generator: generateUKCity,
  },
  {
    id: "street-fr",
    title: "Rue",
    accessory: "Street and number",
    category: "address",
    countries: ["france"],
    generator: generateFrenchStreet,
  },
  {
    id: "postal-fr",
    title: "Code postal",
    accessory: "5-digit postal code",
    category: "address",
    countries: ["france"],
    generator: generateFrenchPostalCode,
  },
  {
    id: "city-fr",
    title: "Ville",
    accessory: "French city",
    category: "address",
    countries: ["france"],
    generator: generateFrenchCity,
  },
  {
    id: "street-us",
    title: "Street",
    accessory: "US street address",
    category: "address",
    countries: ["usa"],
    generator: generateUSStreet,
  },
  {
    id: "city-us",
    title: "City",
    accessory: "US city",
    category: "address",
    countries: ["usa"],
    generator: generateUSCity,
  },
  {
    id: "state-us",
    title: "State",
    accessory: "US state code",
    category: "address",
    countries: ["usa"],
    generator: generateUSState,
  },
  {
    id: "zip-us",
    title: "ZIP",
    accessory: "US ZIP code",
    category: "address",
    countries: ["usa"],
    generator: generateUSZip,
  },
  {
    id: "company-pl",
    title: "Nazwa firmy",
    accessory: "Polish company name",
    category: "company",
    countries: ["poland"],
    generator: generatePolishCompanyName,
  },
  {
    id: "nip",
    title: "NIP",
    accessory: "Tax identification number",
    category: "company",
    countries: ["poland"],
    generator: generateRandomNIP,
  },
  {
    id: "vat-pl",
    title: "VAT",
    accessory: "PL + NIP",
    category: "company",
    countries: ["poland"],
    generator: generateRandomPolishVAT,
  },
  {
    id: "regon",
    title: "REGON",
    accessory: "National business registry number",
    category: "company",
    countries: ["poland"],
    generator: generateRandomREGON,
  },
  {
    id: "company-us",
    title: "Company name",
    accessory: "US company name",
    category: "company",
    countries: ["usa"],
    generator: generateUSCompanyName,
  },
  {
    id: "company-de",
    title: "Firmenname",
    accessory: "German company name",
    category: "company",
    countries: ["germany"],
    generator: generateGermanCompanyName,
  },
  {
    id: "vat-de",
    title: "USt-IdNr",
    accessory: "DE + 9 digits",
    category: "company",
    countries: ["germany"],
    generator: generateGermanVAT,
  },
  {
    id: "company-uk",
    title: "Company name",
    accessory: "UK company name",
    category: "company",
    countries: ["uk"],
    generator: generateUKCompanyName,
  },
  {
    id: "vat-uk",
    title: "VAT number",
    accessory: "GB + 9 digits",
    category: "company",
    countries: ["uk"],
    generator: generateUKVAT,
  },
  {
    id: "company-fr",
    title: "Nom de l'entreprise",
    accessory: "French company name",
    category: "company",
    countries: ["france"],
    generator: generateFrenchCompanyName,
  },
  {
    id: "siren-fr",
    title: "SIREN",
    accessory: "9 digits with Luhn checksum",
    category: "company",
    countries: ["france"],
    generator: generateFrenchSIREN,
  },
  {
    id: "vat-fr",
    title: "Numéro de TVA",
    accessory: "FR + key + SIREN",
    category: "company",
    countries: ["france"],
    generator: generateFrenchVAT,
  },
  {
    id: "iban-de",
    title: "IBAN",
    accessory: "German bank account",
    category: "payment",
    countries: ["germany"],
    generator: generateGermanIBAN,
  },
  {
    id: "iban-uk",
    title: "IBAN",
    accessory: "UK bank account",
    category: "payment",
    countries: ["uk"],
    generator: generateUKIBAN,
  },
  {
    id: "iban-fr",
    title: "IBAN",
    accessory: "French bank account",
    category: "payment",
    countries: ["france"],
    generator: generateFrenchIBAN,
  },
  {
    id: "iban-pl",
    title: "IBAN",
    accessory: "Polish bank account",
    category: "payment",
    countries: ["poland"],
    generator: generateRandomPolishIBAN,
    copyVariants: [{ title: "Copy without spaces", transform: (value) => value.replaceAll(" ", "") }],
  },
  {
    id: "stripe-card",
    title: "Stripe Test Card",
    accessory: "Stripe test PAN",
    category: "payment",
    countries: "global",
    generator: generateStripeTestCard,
    copyVariants: [{ title: "Copy spaced", transform: formatCardNumber }],
  },
  {
    id: "visa-card",
    title: "Visa Card",
    accessory: "Valid Visa test PAN",
    category: "payment",
    countries: "global",
    generator: generateVisaCard,
    copyVariants: [{ title: "Copy spaced", transform: formatCardNumber }],
  },
  {
    id: "mastercard-card",
    title: "MasterCard Card",
    accessory: "Valid Mastercard test PAN",
    category: "payment",
    countries: "global",
    generator: generateMasterCard,
    copyVariants: [{ title: "Copy spaced", transform: formatCardNumber }],
  },
  {
    id: "card-expiry",
    title: "Card expiry",
    accessory: "MM/YY",
    category: "payment",
    countries: "global",
    generator: generateCardExpiry,
  },
  {
    id: "card-cvc",
    title: "Card CVC",
    accessory: "3-digit CVC",
    category: "payment",
    countries: "global",
    generator: generateCardCvc,
  },
  {
    id: "plate-pl",
    title: "Numer rejestracyjny",
    accessory: "Polish license plate",
    category: "vehicle",
    countries: ["poland"],
    generator: generateRandomPolishPlateNumber,
    copyVariants: [{ title: "Copy without spaces", transform: (value) => value.replaceAll(" ", "") }],
  },
];

export function fieldsForCountry(country: CountryId): FieldDefinition[] {
  return fieldCatalog.filter((field) => field.countries === "global" || field.countries.includes(country));
}
